package com.example.fooddeliveryapp.ui.components

import androidx.annotation.DrawableRes
import com.example.fooddeliveryapp.R

internal object FoodDrawableRegistry {
    private val localDrawablesByName = mapOf(
        "foodly_u_borscht_1" to R.drawable.foodly_u_borscht_1,
        "foodly_u_borscht_2" to R.drawable.foodly_u_borscht_2,
        "foodly_u_bowl_1" to R.drawable.foodly_u_bowl_1,
        "foodly_u_bowl_2" to R.drawable.foodly_u_bowl_2,
        "foodly_u_bowl_3" to R.drawable.foodly_u_bowl_3,
        "foodly_u_buns_1" to R.drawable.foodly_u_buns_1,
        "foodly_u_buns_2" to R.drawable.foodly_u_buns_2,
        "foodly_u_burger_1" to R.drawable.foodly_u_burger_1,
        "foodly_u_burger_2" to R.drawable.foodly_u_burger_2,
        "foodly_u_burger_combo_1" to R.drawable.foodly_u_burger_combo_1,
        "burger_classic_cutout" to R.drawable.burger_classic_cutout,
        "burger_crispy_chicken_cutout" to R.drawable.burger_crispy_chicken_cutout,
        "burger_smoky_double_cutout" to R.drawable.burger_smoky_double_cutout,
        "foodly_u_caesar_1" to R.drawable.foodly_u_caesar_1,
        "foodly_u_caesar_2" to R.drawable.foodly_u_caesar_2,
        "foodly_u_cake_1" to R.drawable.foodly_u_cake_1,
        "foodly_u_cake_2" to R.drawable.foodly_u_cake_2,
        "foodly_u_cheesecake_1" to R.drawable.foodly_u_cheesecake_1,
        "foodly_u_cheesecake_2" to R.drawable.foodly_u_cheesecake_2,
        "foodly_u_chicken_box_1" to R.drawable.foodly_u_chicken_box_1,
        "foodly_u_chicken_box_2" to R.drawable.foodly_u_chicken_box_2,
        "foodly_u_chicken_burger_1" to R.drawable.foodly_u_chicken_burger_1,
        "foodly_u_chicken_rice_1" to R.drawable.foodly_u_chicken_rice_1,
        "foodly_u_chicken_set_1" to R.drawable.foodly_u_chicken_set_1,
        "foodly_u_chicken_set_2" to R.drawable.foodly_u_chicken_set_2,
        "foodly_u_chicken_soup_1" to R.drawable.foodly_u_chicken_soup_1,
        "foodly_u_chicken_soup_2" to R.drawable.foodly_u_chicken_soup_2,
        "foodly_u_coffee_1" to R.drawable.foodly_u_coffee_1,
        "foodly_u_coffee_2" to R.drawable.foodly_u_coffee_2,
        "foodly_u_cream_soup_1" to R.drawable.foodly_u_cream_soup_1,
        "foodly_u_cream_soup_2" to R.drawable.foodly_u_cream_soup_2,
        "foodly_u_croissant_1" to R.drawable.foodly_u_croissant_1,
        "foodly_u_croissant_2" to R.drawable.foodly_u_croissant_2,
        "foodly_u_doner_1" to R.drawable.foodly_u_doner_1,
        "foodly_u_doner_2" to R.drawable.foodly_u_doner_2,
        "foodly_u_donuts_1" to R.drawable.foodly_u_donuts_1,
        "foodly_u_donuts_2" to R.drawable.foodly_u_donuts_2,
        "foodly_u_fitness_1" to R.drawable.foodly_u_fitness_1,
        "foodly_u_fitness_2" to R.drawable.foodly_u_fitness_2,
        "foodly_u_fried_chicken_1" to R.drawable.foodly_u_fried_chicken_1,
        "foodly_u_fried_chicken_2" to R.drawable.foodly_u_fried_chicken_2,
        "foodly_u_fries_1" to R.drawable.foodly_u_fries_1,
        "foodly_u_fries_2" to R.drawable.foodly_u_fries_2,
        "foodly_u_greek_1" to R.drawable.foodly_u_greek_1,
        "foodly_u_greek_2" to R.drawable.foodly_u_greek_2,
        "foodly_u_gyros_1" to R.drawable.foodly_u_gyros_1,
        "foodly_u_gyros_2" to R.drawable.foodly_u_gyros_2,
        "foodly_u_hotdog_1" to R.drawable.foodly_u_hotdog_1,
        "foodly_u_hotdog_2" to R.drawable.foodly_u_hotdog_2,
        "foodly_u_hotdog_3" to R.drawable.foodly_u_hotdog_3,
        "foodly_u_icecream_1" to R.drawable.foodly_u_icecream_1,
        "foodly_u_icecream_2" to R.drawable.foodly_u_icecream_2,
        "foodly_u_juice_1" to R.drawable.foodly_u_juice_1,
        "foodly_u_juice_2" to R.drawable.foodly_u_juice_2,
        "foodly_u_kazan_kebab_1" to R.drawable.foodly_u_kazan_kebab_1,
        "foodly_u_lagman_1" to R.drawable.foodly_u_lagman_1,
        "foodly_u_lavash_1" to R.drawable.foodly_u_lavash_1,
        "foodly_u_lavash_2" to R.drawable.foodly_u_lavash_2,
        "foodly_u_lemonade_1" to R.drawable.foodly_u_lemonade_1,
        "foodly_u_lemonade_2" to R.drawable.foodly_u_lemonade_2,
        "foodly_u_lentil_soup_1" to R.drawable.foodly_u_lentil_soup_1,
        "foodly_u_lentil_soup_2" to R.drawable.foodly_u_lentil_soup_2,
        "foodly_u_manti_1" to R.drawable.foodly_u_manti_1,
        "foodly_u_manti_2" to R.drawable.foodly_u_manti_2,
        "foodly_u_mastava_1" to R.drawable.foodly_u_mastava_1,
        "foodly_u_milkshake_1" to R.drawable.foodly_u_milkshake_1,
        "foodly_u_milkshake_2" to R.drawable.foodly_u_milkshake_2,
        "foodly_u_noodles_1" to R.drawable.foodly_u_noodles_1,
        "foodly_u_noodles_2" to R.drawable.foodly_u_noodles_2,
        "foodly_u_nuggets_1" to R.drawable.foodly_u_nuggets_1,
        "foodly_u_nuggets_2" to R.drawable.foodly_u_nuggets_2,
        "foodly_u_omelet_1" to R.drawable.foodly_u_omelet_1,
        "foodly_u_omelet_2" to R.drawable.foodly_u_omelet_2,
        "foodly_u_pancakes_1" to R.drawable.foodly_u_pancakes_1,
        "foodly_u_pancakes_2" to R.drawable.foodly_u_pancakes_2,
        "foodly_u_pizza_1" to R.drawable.foodly_u_pizza_1,
        "foodly_u_pizza_2" to R.drawable.foodly_u_pizza_2,
        "foodly_u_pizza_3" to R.drawable.foodly_u_pizza_3,
        "foodly_u_pizza_4" to R.drawable.foodly_u_pizza_4,
        "foodly_u_pizza_combo_1" to R.drawable.foodly_u_pizza_combo_1,
        "foodly_u_plov_1" to R.drawable.foodly_u_plov_1,
        "foodly_u_plov_2" to R.drawable.foodly_u_plov_2,
        "foodly_u_porridge_1" to R.drawable.foodly_u_porridge_1,
        "foodly_u_porridge_2" to R.drawable.foodly_u_porridge_2,
        "foodly_u_ramen_1" to R.drawable.foodly_u_ramen_1,
        "foodly_u_ramen_2" to R.drawable.foodly_u_ramen_2,
        "foodly_u_rolls_1" to R.drawable.foodly_u_rolls_1,
        "foodly_u_rolls_2" to R.drawable.foodly_u_rolls_2,
        "foodly_u_rolls_3" to R.drawable.foodly_u_rolls_3,
        "foodly_u_samsa_1" to R.drawable.foodly_u_samsa_1,
        "foodly_u_samsa_2" to R.drawable.foodly_u_samsa_2,
        "foodly_u_sandwich_1" to R.drawable.foodly_u_sandwich_1,
        "foodly_u_sandwich_2" to R.drawable.foodly_u_sandwich_2,
        "foodly_u_shashlik_1" to R.drawable.foodly_u_shashlik_1,
        "foodly_u_shashlik_2" to R.drawable.foodly_u_shashlik_2,
        "foodly_u_shawarma_1" to R.drawable.foodly_u_shawarma_1,
        "foodly_u_shawarma_2" to R.drawable.foodly_u_shawarma_2,
        "foodly_u_shawarma_3" to R.drawable.foodly_u_shawarma_3,
        "foodly_u_smoothie_1" to R.drawable.foodly_u_smoothie_1,
        "foodly_u_smoothie_2" to R.drawable.foodly_u_smoothie_2,
        "foodly_u_soda_1" to R.drawable.foodly_u_soda_1,
        "foodly_u_soda_2" to R.drawable.foodly_u_soda_2,
        "foodly_u_sushi_1" to R.drawable.foodly_u_sushi_1,
        "foodly_u_sushi_2" to R.drawable.foodly_u_sushi_2,
        "foodly_u_syrniki_1" to R.drawable.foodly_u_syrniki_1,
        "foodly_u_syrniki_2" to R.drawable.foodly_u_syrniki_2,
        "foodly_u_tea_1" to R.drawable.foodly_u_tea_1,
        "foodly_u_teriyaki_1" to R.drawable.foodly_u_teriyaki_1,
        "foodly_u_vegetarian_1" to R.drawable.foodly_u_vegetarian_1,
        "foodly_u_vegetarian_2" to R.drawable.foodly_u_vegetarian_2,
        "foodly_u_vegetarian_3" to R.drawable.foodly_u_vegetarian_3,
        "foodly_u_water_1" to R.drawable.foodly_u_water_1,
        "foodly_u_wings_1" to R.drawable.foodly_u_wings_1,
        "foodly_u_wings_2" to R.drawable.foodly_u_wings_2,
        "foodly_u_wings_3" to R.drawable.foodly_u_wings_3,
        "foodly_u_wok_1" to R.drawable.foodly_u_wok_1,
        "foodly_u_wok_2" to R.drawable.foodly_u_wok_2,
        "home_dessert" to R.drawable.home_dessert,
        "home_fries" to R.drawable.home_fries,
        "home_hotdog" to R.drawable.home_hotdog,
        "home_pizza" to R.drawable.home_pizza,
        "home_shawarma" to R.drawable.home_shawarma,
        "home_snack" to R.drawable.home_snack,
        "home_wings" to R.drawable.home_wings,
        "restaurant_burger" to R.drawable.restaurant_burger,
        "restaurant_crispy_wings" to R.drawable.restaurant_crispy_wings,
        "restaurant_green" to R.drawable.restaurant_green,
        "restaurant_green_bowl" to R.drawable.restaurant_green_bowl,
        "restaurant_milliy" to R.drawable.restaurant_milliy,
        "restaurant_pizza" to R.drawable.restaurant_pizza,
        "restaurant_pizza_republic" to R.drawable.restaurant_pizza_republic,
        "restaurant_sakura" to R.drawable.restaurant_sakura,
        "restaurant_sakura_box" to R.drawable.restaurant_sakura_box,
        "restaurant_shawarma" to R.drawable.restaurant_shawarma,
        "restaurant_shawarma_house" to R.drawable.restaurant_shawarma_house,
        "restaurant_urban_burger" to R.drawable.restaurant_urban_burger,
        "restaurant_wings" to R.drawable.restaurant_wings,
    )

    @DrawableRes
    fun resolve(model: String): Int? {
        val resourceName = model.androidDrawableResourceName() ?: return null
        return localDrawablesByName[resourceName]
    }
}

private fun String.androidDrawableResourceName(): String? {
    if (!startsWith("android.resource://")) return null
    val path = substringAfter("android.resource://").substringAfter('/')
    val segments = path.split('/').filter { it.isNotBlank() }
    return when {
        segments.size >= 2 && segments[segments.lastIndex - 1] == "drawable" -> segments.last()
        segments.size == 1 && segments.first().all(Char::isDigit).not() -> segments.first()
        else -> null
    }
}
